[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.clean]
command = "rm"
args = ["-f", "tmp*"]

[tasks.test]
command = "bash"
args = ["./test.sh"]
dependencies = ["build"]

[tasks.flow]
dependencies = ["clean", "build", "test"]

