[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.clean]
command = "rm"
args = ["-f", "tmp*"]

[tasks.test]
command = "bash"
args = ["./test.sh"]
dependencies = ["build"]

[tasks.flow]
dependencies = [
    "format",
    "clean",
    "build",
    "test"
]

